---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-tutorial-check-pr
spec:
  pipelineRef:
    name: pipeline-tutorial-check
  params:
    - name: repo_url
      value: {{repo_url}}
    - name: revision
      value: {{revision}}
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
